=== KROU4/BSTU_1_SEM/Барковский КЯР/Лаба номер 12/ex3.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
<xs:element name="games">
<xs:complexType>
<xs:sequence>
    <xs:element name="head">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="gauthor" type="xs:string"/>
        <xs:element name="gtitle" type="xs:string"/>
        <xs:element name="gyear" type="xs:string"/>
        <xs:element name="gstory" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="game">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="author" type="xs:string"/>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="year" type="xs:string"/>
        <xs:element name="story" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="game">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="author" type="xs:string"/>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="year" type="xs:string"/>
        <xs:element name="story" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="game">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="author" type="xs:string"/>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="year" type="xs:string"/>
        <xs:element name="story" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== KROU4/BSTU_1_SEM/Барковский КЯР/Лаба номер 12/indexSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="forXML.css"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ex3.xsd">
    <head>
        <gauthor>Игра</gauthor>
        <gtitle>Издатель</gtitle>
        <gyear>Год выхода</gyear>
        <gstory>Краткий сюжет</gstory>
    </head>
    <game>
        <author>Stray</author>
        <title>Annapurna Interactive</title>
        <year>2022</year>
        <story>Игра представляет собой приключенческую игру от третьего лица. В ней есть элементы открытого мира, а также упор, сделанный на атмосферу и искусство. Игрок, управляя рыжим котом, должен решать головоломки для того, чтобы продвигаться по сюжету, перемещая препятствия и перебираясь по платформам. Протагониста сопровождает дрон-спутник по имени B-12 (Б-12), который может помочь, переводя язык роботов и храня предметы, найденные по всему миру. Одни из врагов игры — зурки (англ. Zurks), которые будут нападать на игрока свирепыми роями.</story>
    </game>
    <game>
        <author>The Last of Us</author>
        <title>Sony Computer Entertainment</title>
        <year>2014</year>
        <story>Действие основной части происходит спустя 20 лет после глобальной катастрофы — пандемии, вызванной мутировавшим грибом кордицепсом. Согласно сюжету, кордицепс попадает в человеческий организм в виде спор в результате вдыхания, через кровь или слюну заражённого. Затем гриб вызывает необратимые изменения в человеческом организме — жертва теряет разум и превращается в подобие зомби. Пандемия привела к упадку цивилизации и гибели большей части населения США и всей Земли. Часть выживших укрывается в изолированных карантинных зонах, охраняемых военными. Города за пределами карантинных зон превратились в опасные руины, населённые заражёнными, бандитами и каннибалами. Террористическая организация «Цикады» (в оригинале «Светлячки» от англ. Fireflies) пытается поднять население карантинных зон на восстание против военных, а также стремится разработать вакцину против инфекции.</story>
    </game>
    <game>
        <author>Counter-Strike: Source</author>
        <title>Valve</title>
        <year>2004</year>
        <story>Counter-Strike: Source (сокращается до CS: Source и CS:S) — компьютерная игра в жанре многопользовательского командного шутера от первого лица, разработанная компаниями Valve и Turtle Rock Studios; ремейк Counter-Strike, модификации 1999 года для игры Half-Life. Построенная на игровом движке Source, игра была выпущена в 2004 году изначально в комплекте с Half-Life 2, однако позже появились и отдельные её издания.</story>
    </game>
</games>
